### ISSUE TITLE
Undefined method while building template (w/--sync-only)

### ISSUE THREAD

**Issue by thor** [envygeeks/docker-template#15]
In relation to jekyll/docker#90 and its missing `rsync`-package, I thought I'd post the bug here so that we could perhaps get it added sooner rather than later. :)

~~~
/home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/metadata.rb:441:in `method_missing': undefined method `as_hash' for #<Docker::Template::Metadata:0x00000002d97f40> (NoMethodError)
	from (erb):4:in `_binding'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/normal.rb:35:in `copy_dockerfile'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/normal.rb:23:in `setup_context'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:194:in `block in setup'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:192:in `map'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:192:in `setup'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:127:in `build'
	from /usr/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /usr/lib/ruby/2.3.0/set.rb:306:in `each'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:24:in `map'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:24:in `block in build'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:86:in `with_profiling'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:23:in `build'
	from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/thor/.bundler/ruby/2.3.0/docker-template-5bda91ef4e31/bin/docker-template:25:in `<top (required)>'
	from /usr/lib/ruby/gems/2.3.0/bin/docker-template:23:in `load'
	from /usr/lib/ruby/gems/2.3.0/bin/docker-template:23:in `<main>'
~~~

**Comment by envygeeks** [comment]
This is resolved with the latest push to master.
